INSERT INTO CATEGORIAS  VALUES(1, 'Alimentação');
INSERT INTO CATEGORIAS  VALUES(2, 'Transporte');
INSERT INTO CATEGORIAS  VALUES(3, 'Vestuario');
INSERT INTO CATEGORIAS  VALUES(4, 'Cuidados Pessoais');
INSERT INTO CATEGORIAS  VALUES(5, 'Moradia');
INSERT INTO CATEGORIAS  VALUES(6, 'Lazer');
INSERT INTO CATEGORIAS  VALUES(7, 'Educacão');
INSERT INTO CATEGORIAS  VALUES(8, 'Compras');
INSERT INTO CATEGORIAS  VALUES(9, 'Diversão');


INSERT INTO DESPESA  VALUES(1, '2022-06-14' , 'Internet',  'teste', 1234.00, 1);
