INSERT INTO CATEGORIAS (name) VALUES( 'Alimentação');
INSERT INTO CATEGORIAS (name) VALUES( 'Transporte');
INSERT INTO CATEGORIAS (name) VALUES( 'Vestuario');
INSERT INTO CATEGORIAS (name) VALUES( 'Cuidados Pessoais');
INSERT INTO CATEGORIAS (name) VALUES( 'Moradia');
INSERT INTO CATEGORIAS (name) VALUES( 'Lazer');
INSERT INTO CATEGORIAS (name) VALUES( 'Educacão');
INSERT INTO CATEGORIAS (name) VALUES( 'Compras');
INSERT INTO CATEGORIAS (name) VALUES( 'Diversão');

 INSERT INTO DESPESA (data, descricao, obs,valor, categoria_codigo ) VALUES( '2022-06-14' , 'Internet',  'teste', 1234.00, 1);
 INSERT INTO DESPESA (data, descricao, obs,valor, categoria_codigo ) VALUES( '2022-06-14' , 'Sabão',  'teste', 1234.00, 1);
 INSERT INTO DESPESA (data, descricao, obs,valor, categoria_codigo ) VALUES( '2022-06-14' , 'PC',  'teste', 1234.00, 1);
 INSERT INTO DESPESA (data, descricao, obs,valor, categoria_codigo ) VALUES( '2022-06-14' , 'caneta',  'teste', 1234.00, 1);
 INSERT INTO DESPESA (data, descricao, obs,valor, categoria_codigo ) VALUES( '2022-06-14' , 'lapis',  'teste', 1234.00, 1);
 INSERT INTO DESPESA (data, descricao, obs,valor, categoria_codigo ) VALUES( '2022-06-14' , 'celular',  'teste', 1234.00, 1);
 INSERT INTO DESPESA (data, descricao, obs,valor, categoria_codigo ) VALUES( '2022-06-14' , 'mouse',  'teste', 1234.00, 1);
 INSERT INTO DESPESA (data, descricao, obs,valor, categoria_codigo ) VALUES( '2022-06-14' , 'internet',  'teste', 1234.00, 1);
 INSERT INTO DESPESA (data, descricao, obs,valor, categoria_codigo ) VALUES( '2022-06-14' , 'internet',  'teste', 1234.00, 1);
 INSERT INTO DESPESA (data, descricao, obs,valor, categoria_codigo ) VALUES( '2022-06-14' , 'internet',  'teste', 1234.00, 1);
 INSERT INTO DESPESA (data, descricao, obs,valor, categoria_codigo ) VALUES( '2022-06-14' , 'internet',  'teste', 1234.00, 1);
 INSERT INTO DESPESA (data, descricao, obs,valor, categoria_codigo ) VALUES( '2022-06-14' , 'internet',  'teste', 1234.00, 1);
